### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8a in position 8: illegal multibyte sequence

### ISSUE THREAD

**Issue by YuweiZ** [vincentsarago/lambda-pyskel#1]
Hi @vincentsarago ,
thank you for providing this script for zip package
I met this following issue, and it still occured after I had added encoding='utf-8' in line 32 in cli.py
(python36) C:\Users\Makeone>lps Bob --template gdal
Traceback (most recent call last):
  File "c:\users\makeone\anaconda3\envs\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\makeone\anaconda3\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Makeone\Anaconda3\envs\python36\Scripts\lps.exe\__main__.py", line 9, in <module>
  File "c:\users\makeone\anaconda3\envs\python36\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\makeone\anaconda3\envs\python36\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\makeone\anaconda3\envs\python36\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\makeone\anaconda3\envs\python36\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\makeone\anaconda3\envs\python36\lib\site-packages\lambda_pyskel\scripts\cli.py", line 32, in create
    s = f.read().replace("pyskel", name)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xdb in position 8: illegal multibyte sequence

**Comment by YuweiZ** [comment]
I fixed it by adding    "   encoding='ISO-8859-1'    "

**Comment by vincentsarago** [comment]
Hi @YuweiZ, 
yeah this happened to me some time when I had `.DS_Store` file in my templates directories. Can you please explain a bit more about the fix, so I'll update the package

**Comment by YuweiZ** [comment]
@vincentsarago Actually,When I perfromed the command "lps xxx --template gdal" in Linux,  return this message "Command 'lps' not found, but there are 26 similar ones.", So I move to windows to generate template file by adding " encoding='ISO-8859-1' " and copied it to linux and then ran make. At last I got "Makefile:5: recipe for target 'build' failed make: *** [build] Error 1" the zip file was generated,but I'm not sure it's completed or not as it is only 23 MB.  do you have any clue with this?

**Comment by vincentsarago** [comment]
🤔 if the zip was generated and copied locally it should be fine. To me it seems the docker deamon just could stop and clean the instance (may need to do `make clean`). The `.zip`file should be around 23.7Mb so seems you are fine.

**Comment by vincentsarago** [comment]
about the name of the command, I'm guilty I didn't check if there was any other known command with this name. you may need to create your own alias in linux.

**Comment by YuweiZ** [comment]
Hej @vincentsarago ,  
Thank you so much for the help, I will try to test the zip file then.:)
